name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Push Multi-Arch Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub (for cache)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image (with cache)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ secrets.GH_USERNAME }}/pawcho:${{ steps.extract_tag.outputs.VERSION }}
            ghcr.io/${{ secrets.GH_USERNAME }}/pawcho:latest
          cache-from: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cache:buildkit
          cache-to: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cache:buildkit,mode=max
          provenance: false
          sbom: false

      - name: Install Trivy
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: image
          image-ref: ghcr.io/${{ secrets.GH_USERNAME }}/pawcho:${{ steps.extract_tag.outputs.VERSION }}
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          ignore-policy: .trivyignore.yml
          format: table
          exit-code: 1

      - name: Fail if vulnerabilities found
        if: failure()
        run: echo "High or Critical vulnerabilities found. Failing build." && exit 1
